[package]
name = "v14-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.23"
core = { path = "../../core_v14", package = "core_v14" }
anyhow = "1.0.44"
