[package]
name = "desub-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-runtime = { package = "sp-runtime",  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
sp-core = { package = "sp-core",  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
serde = { version = "1", features = [ "derive" ] }


